export { runMigrations } from "./db/migrations.js";
export { RelayRepository } from "./db/repositories/relayRepository.js";
export { registerAuditRoutes } from "./routes/audit.routes.js";
export { registerAuthRoutes } from "./routes/auth.routes.js";
export { registerFileRoutes } from "./routes/file.routes.js";
export { registerFriendRoutes } from "./routes/friend.routes.js";
export type { InviteSecurityContext } from "./routes/inviteResponse.js";
export { registerRoomRoutes } from "./routes/room.routes.js";
export * from "./routes/security.routes.js";
export { registerTeamRoutes } from "./routes/team.routes.js";
export { generateBootstrapPin } from "./security/bootstrapPin.js";
export { FixedWindowRateLimiter } from "./security/rateLimiter.js";
export * from "./security/identity.js";
export * from "./security/identityLifecycle.js";
export * from "./security/identityStore.js";
export * from "./security/rotation.js";
export { ConnectionRegistry } from "./sync/connectionRegistry.js";
export { handleSyncSocket, startInQueueTurn } from "./sync/syncServer.js";
export type { SyncTimerHost } from "./sync/syncServer.js";
// Both runtimes share the same presence service and registry.
export { PresenceRegistry } from "./sync/presenceRegistry.js";
export type { PresenceEntry, PresenceTarget } from "./sync/presenceRegistry.js";
export { PresenceService } from "./sync/presenceService.js";
export { CrdtDocManager, CRDT_TEXT_KEY } from "./sync/crdtDocManager.js";
export type { CrdtMaterializedEvent, CrdtUpdatedBy } from "./sync/crdtDocManager.js";
export { createRelayCore, createCrdtMaterializedHandler, createCrdtRepositoryPort } from "./relayCore.js";
export type { PreparedStatement, RelayDb, SqlJsLocator, SqlRow } from "./db/sqlJsAdapter.js";
export type { RelayCoreOptions } from "./relayCore.js";
export { scheduleStorageBackfill, reclaimDatabaseSpace } from "./services/storageMaintenance.js";
export type { StorageBackfillHandle, StorageMaintenanceTimerHost } from "./services/storageMaintenance.js";
// Export only runtime-neutral blob helpers to the embedded bundle.
export { blobKeyForBytes, isValidBlobKey, shardedRelativePath } from "./storage/blobStore.js";
export type { BlobStore } from "./storage/blobStore.js";
export type { ContentWriteService } from "./storage/contentWriteService.js";
export { isRawHttpResponse } from "./services/rawHttpResponse.js";
export { authenticateBeforeBody, bodyLimitFor, bodyTooLargeError, corsHeadersFor } from "./services/httpPolicy.js";
