export { runMigrations } from "./db/migrations.js";
export { RelayRepository } from "./db/repositories/relayRepository.js";
export { registerAuthRoutes } from "./routes/auth.routes.js";
export { registerFileRoutes } from "./routes/file.routes.js";
export { registerFriendRoutes } from "./routes/friend.routes.js";
export type { InviteSecurityContext } from "./routes/inviteResponse.js";
export { registerRoomRoutes } from "./routes/room.routes.js";
export * from "./routes/security.routes.js";
export { registerTeamRoutes } from "./routes/team.routes.js";
export { generateBootstrapPin } from "./security/bootstrapPin.js";
export { FixedWindowRateLimiter } from "./security/rateLimiter.js";
export * from "./security/identity.js";
export * from "./security/identityLifecycle.js";
export * from "./security/identityStore.js";
export * from "./security/rotation.js";
export { ConnectionRegistry } from "./sync/connectionRegistry.js";
export { handleSyncSocket } from "./sync/syncServer.js";
export { createRelayCore } from "./relayCore.js";
export type { PreparedStatement, RelayDb, SqlJsLocator, SqlRow } from "./db/sqlJsAdapter.js";
export type { RelayCoreOptions } from "./relayCore.js";
